### ISSUE TITLE
How can I test my local model?

### ISSUE THREAD

**Issue by smile2game** [huggingface/optimum-benchmark#119]
I want to test my own model named Qwen-7B,but how can I write my yaml?This is what it is now.
```defaults:
  - backend: pytorch
  - launcher: process
  - benchmark: inference
  - experiment # inheriting experiment schema
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

experiment_name: pytorch_qwen

backend:
  model: /root/autodl-tmp/Qwen/checkpoint-init/qwen/Qwen-7B
  device: cuda

hydra:
  run:
    dir: runs/${experiment_name}
  sweep:
    dir: sweeps/${experiment_name}
  job:
    chdir: true
    env_set:
      OVERRIDE_BENCHMARKS: 1
      CUDA_VISIBLE_DEVICES: 0
      CUDA_DEVICE_ORDER: PCI_BUS_ID
```
But I just get this result,that's not what I want.
``` 
optimum-benchmark --config-dir ./ --config-name pytorch_qwen
Error executing job with overrides: []
Traceback (most recent call last):
  File "/root/miniconda3/bin/optimum-benchmark", line 33, in <module>
    sys.exit(load_entry_point('optimum-benchmark', 'console_scripts', 'optimum-benchmark')())
  File "/root/miniconda3/lib/python3.8/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/root/miniconda3/lib/python3.8/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/root/miniconda3/lib/python3.8/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/root/miniconda3/lib/python3.8/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/root/miniconda3/lib/python3.8/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/root/miniconda3/lib/python3.8/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/root/miniconda3/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/root/miniconda3/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/root/miniconda3/lib/python3.8/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/root/autodl-tmp/optimum-benchmark/optimum_benchmark/cli.py", line 74, in benchmark_cli
    experiment_config: ExperimentConfig = OmegaConf.to_object(experiment_config)
  File "/root/miniconda3/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 594, in to_object
    return OmegaConf.to_container(
  File "/root/miniconda3/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 573, in to_container
    return BaseContainer._to_content(
  File "/root/miniconda3/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 288, in _to_content
    return conf._to_object()
  File "/root/miniconda3/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 755, in _to_object
    v = OmegaConf.to_object(node)
  File "/root/miniconda3/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 594, in to_object
    return OmegaConf.to_container(
  File "/root/miniconda3/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 573, in to_container
    return BaseContainer._to_content(
  File "/root/miniconda3/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 288, in _to_content
    return conf._to_object()
  File "/root/miniconda3/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 765, in _to_object
    result = object_type(**init_field_items)
  File "<string>", line 32, in __init__
  File "/root/autodl-tmp/optimum-benchmark/optimum_benchmark/backends/pytorch/config.py", line 67, in __post_init__
    super().__post_init__()
  File "/root/autodl-tmp/optimum-benchmark/optimum_benchmark/backends/config.py", line 88, in __post_init__
    self.task = infer_task_from_model_name_or_path(self.model)
  File "/root/autodl-tmp/optimum-benchmark/optimum_benchmark/task_utils.py", line 158, in infer_task_from_model_name_or_path
    raise RuntimeError("Cannot infer the task from a local directory yet, please specify the task manually.")
RuntimeError: Cannot infer the task from a local directory yet, please specify the task manually.
```

**Comment by IlyasMoutawwakil** [comment]
> RuntimeError: Cannot infer the task from a local directory yet, please specify the task manually.
specify the task manually `backend.task=text-generation` since inferring task from local models is not implemented.
