### ISSUE TITLE
Testing Qwen-7B.    >>>   AttributeError: 'NoneType' object has no attribute 'to_dict'

### ISSUE THREAD

**Issue by smile2game** [huggingface/optimum-benchmark#120]
I want to test Qwen-7B model on hub.But when I using the pytorch_qwen.yaml which I wrote myself like this.I got the error.
By the way,I can test bert correctly.
```
defaults:
  - backend: pytorch
  - launcher: process
  - benchmark: inference
  - experiment # inheriting experiment schema
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

experiment_name: pytorch_qwen

backend:
  model: Qwen/Qwen-7B
  # model: /root/autodl-tmp/Qwen/checkpoint-init/qwen/Qwen-7B
  device: cuda
  # task: text-generation
# launcher:
#   device_isolation: true
# benchmark:
#   input_shapes:
#     batch_size: 1
#     sequence_length: 256
#   new_tokens: 1000
hydra:
  run:
    dir: runs/${experiment_name}
  sweep:
    dir: sweeps/${experiment_name}
  job:
    chdir: true
    env_set:
      OVERRIDE_BENCHMARKS: 1
      CUDA_VISIBLE_DEVICES: 0
      CUDA_DEVICE_ORDER: PCI_BUS_ID
```

outputs:
``` 
(base) root@autodl-container-809011af9e-c6b7ec5f:~/autodl-tmp/test-result# optimum-benchmark --config-dir ./ --config-name pytorch_qwen
[2024-02-10 18:31:27,933][launcher][INFO] - ََAllocating process launcher
[2024-02-10 18:31:27,934][process][INFO] -      + Setting multiprocessing start method to spawn.
[2024-02-10 18:31:27,952][process][INFO] -      + Launched worker process with PID 1146.
[2024-02-10 18:31:30,733][numexpr.utils][INFO] - Note: NumExpr detected 40 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2024-02-10 18:31:30,932][datasets][INFO] - PyTorch version 2.0.0+cu118 available.
[2024-02-10 18:31:31,230][backend][INFO] - َAllocating pytorch backend
Loading Qwen/Qwen-7B requires to execute some code in that repo, you can inspect the content of the repository at https://hf.co/Qwen/Qwen-7B. You can dismiss this prompt by passing `trust_remote_code=True`.
Do you accept? [y/N] Loading Qwen/Qwen-7B requires to execute some code in that repo, you can inspect the content of the repository at https://hf.co/Qwen/Qwen-7B. You can dismiss this prompt by passing `trust_remote_code=True`.
Do you accept? [y/N] [2024-02-10 18:31:32,808][experiment][ERROR] - Error during backend allocation: 'NoneType' object has no attribute 'to_dict'
Process Process-1:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/miniconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/autodl-tmp/optimum-benchmark/optimum_benchmark/launchers/process/launcher.py", line 54, in target
    out = fn(*args)
  File "/root/autodl-tmp/optimum-benchmark/optimum_benchmark/experiment.py", line 89, in run
    raise e
  File "/root/autodl-tmp/optimum-benchmark/optimum_benchmark/experiment.py", line 86, in run
    backend: Backend = backend_factory(backend_config)
  File "/root/autodl-tmp/optimum-benchmark/optimum_benchmark/backends/pytorch/backend.py", line 44, in __init__
    super().__init__(config)
  File "/root/autodl-tmp/optimum-benchmark/optimum_benchmark/backends/base.py", line 84, in __init__
    self.model_shapes = extract_transformers_shapes_from_artifacts(
  File "/root/autodl-tmp/optimum-benchmark/optimum_benchmark/backends/transformers_utils.py", line 65, in extract_transformers_shapes_from_artifacts
    config_dict = {k: v for k, v in config.to_dict().items() if v is not None}
AttributeError: 'NoneType' object has no attribute 'to_dict'
[2024-02-10 18:31:33,355][process][ERROR] -     + Worker process exited with code 1, forwarding...
```
The version now is:
```
torch                     2.0.0+cu118              
torchvision               0.15.1+cu118        
Cuda compilation tools, release 11.8, V11.8.89
optimum-benchmark         0.0.2                     
transformers              4.32.0 
```
Maybe I should add  trust_remote_code=True in my .yaml,but I'm not sure where to add.

**Comment by IlyasMoutawwakil** [comment]
this seems like an error caused by not finding the model's pretrained config, I don't know if you included it in your local directory as well. Try `AutoConfig.from_pretrained("/root/autodl-tmp/Qwen/checkpoint-init/qwen/Qwen-7B")` and see if it works.
If `trust_remote_directory=True` is needed, then add it to `backend.hub_kwargs.trust_remote_directory=true`.

**Comment by smile2game** [comment]
I have given up to use my local model.I use `model: Qwen/Qwen-7B` to load the model which is online.Then I get the error before.
And I also found that if I change the model to chatglm or baichuan,I will get the same error.

**Comment by IlyasMoutawwakil** [comment]
I just tested `Qwen/Qwen-7B` and it works when I add `trust_remote_code=True`, so please add it to your config:
```
backend:
  model: Qwen/Qwen-7B
  hub_kwargs:
    trust_remote_code: true
```
as I explained before, the custom configuration used by these models can't be accessed without explicitly telling it to trust remote code.

**Comment by smile2game** [comment]
Thank you very much!I just add the `backend.hub_kwargs.trust_remote_code=true` in my yaml.It can run correctly.
The reason maybe is that some code in the directory should be executed but I don't make it be trusted before.
All in all,your answer helps me resolve the problem.Hope you have a nice day!Happy Chinese New Year for you!

**Comment by smile2game** [comment]
Would you have a doc for users to read?It can help me to find the method next time.
Maybe I need to learn optimum at first.Can you give me some suggestions?

**Comment by IlyasMoutawwakil** [comment]
Happy Chinese new year to you as well 🤗
I admit the library is still undocumented, I will probably do a documentation sprint very soon.
Right now you can check the configuration dataclass of each component you're using, as it contains all of the features supported it. In this case you'd need to check `optimum_benchmark.backends.pytorch.config.PytorchConfig`

**Comment by smile2game** [comment]
Thanks for everything and appreciate your hard working!Good luck to you!
