### ISSUE TITLE
TypeError: argument of type 'GPTQConfig' is not iterable

### ISSUE THREAD

**Issue by lopozz** [huggingface/optimum-benchmark#125]
I wanted to run the TheBloke/phi-2-dpo-GPTQ model. Here are the steps I followed:

```
git clone https://github.com/huggingface/optimum-benchmark.git
cd optimum-benchmark
pip install -e .
```

```
optimum-benchmark --config-dir my_configs/ --config-name pytorch_phi
```

with this file in the my_configs directory

```
defaults:
  - backend: pytorch # default backend
  - launcher: process # default launcher
  - benchmark: inference # default benchmark
  - experiment # inheriting experiment schema
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

experiment_name: pytorch_phi

backend:
  device: cuda
  device_ids: 0
  no_weights: true
  model: TheBloke/phi-2-dpo-GPTQ
  hub_kwargs:
    trust_remote_code: true

launcher:
  device_isolation: true

benchmark:
  input_shapes:
    batch_size: 1
    sequence_length: 256
  new_tokens: 1000

# hydra/cli specific settings
hydra:
  run:
    # where to store run results
    dir: runs/${experiment_name}
  sweep:
    # where to store sweep results
    dir: sweeps/${experiment_name}
  job:
    # change working directory to the run directory
    chdir: true
    env_set:
      # set environment variable OVERRIDE_BENCHMARKS to 1
      # to not skip benchmarks that have been run before
      OVERRIDE_BENCHMARKS: 1
```

outputs:

```
[2024-02-16 16:16:46,177][inference][WARNING] - `new_tokens` is deprecated. Use `max_new_tokens` and `min_new_tokens` instead. Setting `max_new_tokens` and `min_new_tokens` to `new_tokens`.
[2024-02-16 16:16:46,351][launcher][INFO] - ََAllocating process launcher
[2024-02-16 16:16:46,351][process][INFO] -      + Setting multiprocessing start method to spawn.
[2024-02-16 16:16:46,354][process][INFO] -      + Launched worker process with PID 404641.
[2024-02-16 16:16:46,355][isolation][INFO] -    + Launched device(s) isolation process 404642.
[2024-02-16 16:16:48,818][datasets][INFO] - PyTorch version 2.2.0 available.
[2024-02-16 16:16:48,953][backend][INFO] - َAllocating pytorch backend
[2024-02-16 16:16:48,953][backend][INFO] -      + Setting random seed to 42
[2024-02-16 16:16:51,212][pytorch][INFO] -      + Using AutoModel class AutoModelForCausalLM
[2024-02-16 16:16:51,212][pytorch][INFO] -      + Processing quantization config
[2024-02-16 16:16:51,212][pytorch][INFO] -      + Processing GPTQ config
[2024-02-16 16:16:51,212][pytorch][INFO] -      + Creating backend temporary directory
[2024-02-16 16:16:51,213][pytorch][INFO] -      + Loading model with no weights
[2024-02-16 16:16:51,213][pytorch][INFO] -      + Creating no weights model state_dict
[2024-02-16 16:16:51,214][experiment][ERROR] - Error during backend allocation: argument of type 'GPTQConfig' is not iterable
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/navya/Git/optimum-benchmark/optimum_benchmark/launchers/process/launcher.py", line 54, in target
    out = fn(*args)
  File "/home/navya/Git/optimum-benchmark/optimum_benchmark/experiment.py", line 104, in run
    raise e
  File "/home/navya/Git/optimum-benchmark/optimum_benchmark/experiment.py", line 101, in run
    backend: Backend = backend_factory(backend_config)
  File "/home/navya/Git/optimum-benchmark/optimum_benchmark/backends/pytorch/backend.py", line 72, in __init__
    self.load_model_with_no_weights()
  File "/home/navya/Git/optimum-benchmark/optimum_benchmark/backends/pytorch/backend.py", line 216, in load_model_with_no_weights
    self.create_no_weights_model()
  File "/home/navya/Git/optimum-benchmark/optimum_benchmark/backends/pytorch/backend.py", line 188, in create_no_weights_model
    if self.is_exllamav2:
  File "/home/navya/Git/optimum-benchmark/optimum_benchmark/backends/pytorch/backend.py", line 293, in is_exllamav2
    and "exllama_config" in self.quantization_config
TypeError: argument of type 'GPTQConfig' is not iterable
```

**Comment by IlyasMoutawwakil** [comment]
Hi! this change was introduced as part of a refactoring I'm doing to support python API usage.
Please use this branch for now if you're only interested in CLI https://github.com/huggingface/optimum-benchmark/tree/0.0.1
I will fix this issue in my next PR.

**Comment by IlyasMoutawwakil** [comment]
@lopozz if you want GPTQ quantization scheme to be continuously tested with the new API, please feel free to open a PR adding a configuration to the test configs, I would be glad to review it.

**Comment by lopozz** [comment]
Sure I was thinking about it :)

**Comment by IlyasMoutawwakil** [comment]
@lopozz I fixed it as part of another PR, but still not tested.
