### ISSUE TITLE
How to set trt llm backend parameters

### ISSUE THREAD

**Issue by Yuchen-Cao** [huggingface/optimum-benchmark#138]
I am trying to run the trt_llama example: https://github.com/huggingface/optimum-benchmark/blob/main/examples/trt_llama.yaml

It seems optimem-benchmark will automatically transform the huggingface model to inference engine file then benchmarking its performance. When we use tensorrt llm, there is a model "build" process (during which we set some quantization parameters) in order to get the `.engine file`. How can we set these parameters when using optimum benchmark?

**Comment by Yuchen-Cao** [comment]
And btw... I got an error when trying to run this example:
```
root@8ab0446e0cfd:/opt/optimum-benchmark# optimum-benchmark --config-dir examples/ --config-name trt_llama
[2024-02-24 17:22:59,176][inference][WARNING] - `new_tokens` is deprecated. Use `max_new_tokens` and `min_new_tokens` instead. Setting `max_new_tokens` and `min_new_tokens` to `new_tokens`.
[2024-02-24 17:23:00,463][backend][WARNING] - `device_ids` was not specified, using all available GPUs.
[2024-02-24 17:23:00,468][backend][WARNING] - `device_ids` is now set to `0` based on system configuration.
[2024-02-24 17:23:00,470][launcher][INFO] - ََAllocating process launcher
[2024-02-24 17:23:00,470][process][INFO] -      + Setting multiprocessing start method to spawn.
[2024-02-24 17:23:00,473][process][INFO] -      + Launched worker process(es) with PID(s): [1004]
[PROC-0][2024-02-24 17:23:09,542][backend][INFO] - َAllocating tensorrt-llm backend
[PROC-0][2024-02-24 17:23:09,542][backend][INFO] -      + Setting random seed to 42
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:389: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:394: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
[PROC-0][2024-02-24 17:23:11,568][tensorrt-llm][INFO] -         + Using TRTLLMModel class LlamaForCausalLM
[PROC-0][2024-02-24 17:23:11,568][tensorrt-llm][INFO] -         + Loading pretrained TRTLLMModel
[PROC-0][2024-02-24 17:23:13,592][optimum.nvidia.builder][WARNING] - Quantization descriptor was None, assuming no quantization will be applied. If you want to change this behaviour, please use TRTEngineBuilder.with_quantization_schema()
[PROC-0][2024-02-24 17:23:21,845][experiment][ERROR] - Error during backend allocation: [Errno 22] Invalid argument
[2024-02-24 17:23:23,377][experiment][ERROR] - Error during experiment launching: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/opt/optimum-benchmark/optimum_benchmark/launchers/process/launcher.py", line 58, in entrypoint
    worker_output = worker(*worker_args)
  File "/opt/optimum-benchmark/optimum_benchmark/experiment.py", line 117, in run
    raise e
  File "/opt/optimum-benchmark/optimum_benchmark/experiment.py", line 114, in run
    backend: Backend = backend_factory(backend_config)
  File "/opt/optimum-benchmark/optimum_benchmark/backends/tensorrt_llm/backend.py", line 25, in __init__
    self.load_trtmodel_from_pretrained()
  File "/opt/optimum-benchmark/optimum_benchmark/backends/tensorrt_llm/backend.py", line 47, in load_trtmodel_from_pretrained
    self.pretrained_model = self.trtmodel_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/hub_mixin.py", line 157, in from_pretrained
    return cls._from_pretrained(
  File "/opt/optimum-nvidia/src/optimum/nvidia/runtime.py", line 154, in _from_pretrained
    builder.build(engine_folder, optimization_level)
  File "/opt/optimum-nvidia/src/optimum/nvidia/builder.py", line 405, in build
    build_func(shards_info, files, output_path, optimization_level)
  File "/opt/optimum-nvidia/src/optimum/nvidia/builder.py", line 418, in _build_serial
    self._build_engine_for_rank(shard, weights, output_path, opt_level, is_parallel=False)
  File "/opt/optimum-nvidia/src/optimum/nvidia/builder.py", line 500, in _build_engine_for_rank
    self._weight_adapter.from_safetensors(weight.files, model, config, build_config, qconfig, shard)
  File "/opt/optimum-nvidia/src/optimum/nvidia/models/llama.py", line 193, in from_safetensors
    accessor = SafetensorsAccessor.from_files(paths)
  File "/opt/optimum-nvidia/src/optimum/nvidia/weights/safetensors.py", line 48, in from_files
    mm.madvise(MADV_SEQUENTIAL | MADV_HUGEPAGE | MADV_WILLNEED)
OSError: [Errno 22] Invalid argument

Error executing job with overrides: []
Traceback (most recent call last):
  File "/opt/optimum-benchmark/optimum_benchmark/cli.py", line 61, in benchmark_cli
    benchmark_report: BenchmarkReport = launch(experiment_config=experiment_config)
  File "/opt/optimum-benchmark/optimum_benchmark/experiment.py", line 188, in launch
    raise e
  File "/opt/optimum-benchmark/optimum_benchmark/experiment.py", line 184, in launch
    output = launcher.launch(run, benchmark_config, backend_config)
  File "/opt/optimum-benchmark/optimum_benchmark/launchers/process/launcher.py", line 42, in launch
    while not process_context.join():
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 163, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/opt/optimum-benchmark/optimum_benchmark/launchers/process/launcher.py", line 58, in entrypoint
    worker_output = worker(*worker_args)
  File "/opt/optimum-benchmark/optimum_benchmark/experiment.py", line 117, in run
    raise e
  File "/opt/optimum-benchmark/optimum_benchmark/experiment.py", line 114, in run
    backend: Backend = backend_factory(backend_config)
  File "/opt/optimum-benchmark/optimum_benchmark/backends/tensorrt_llm/backend.py", line 25, in __init__
    self.load_trtmodel_from_pretrained()
  File "/opt/optimum-benchmark/optimum_benchmark/backends/tensorrt_llm/backend.py", line 47, in load_trtmodel_from_pretrained
    self.pretrained_model = self.trtmodel_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/hub_mixin.py", line 157, in from_pretrained
    return cls._from_pretrained(
  File "/opt/optimum-nvidia/src/optimum/nvidia/runtime.py", line 154, in _from_pretrained
    builder.build(engine_folder, optimization_level)
  File "/opt/optimum-nvidia/src/optimum/nvidia/builder.py", line 405, in build
    build_func(shards_info, files, output_path, optimization_level)
  File "/opt/optimum-nvidia/src/optimum/nvidia/builder.py", line 418, in _build_serial
    self._build_engine_for_rank(shard, weights, output_path, opt_level, is_parallel=False)
  File "/opt/optimum-nvidia/src/optimum/nvidia/builder.py", line 500, in _build_engine_for_rank
    self._weight_adapter.from_safetensors(weight.files, model, config, build_config, qconfig, shard)
  File "/opt/optimum-nvidia/src/optimum/nvidia/models/llama.py", line 193, in from_safetensors
    accessor = SafetensorsAccessor.from_files(paths)
  File "/opt/optimum-nvidia/src/optimum/nvidia/weights/safetensors.py", line 48, in from_files
    mm.madvise(MADV_SEQUENTIAL | MADV_HUGEPAGE | MADV_WILLNEED)
OSError: [Errno 22] Invalid argument


Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by IlyasMoutawwakil** [comment]
I'm not sure how much of the quantization configuration `optimum-nvidia` exposes, you can ask there https://github.com/huggingface/optimum-nvidia, the only parameter I can see in the readme/doc is `use_fp8=True` which handles the quantization logic, other quantization schemes seem to be in progress https://github.com/huggingface/optimum-nvidia/blob/main/src/optimum/nvidia/quantization/awq.py

**Comment by Yuchen-Cao** [comment]
> I'm not sure how much of the quantization configuration `optimum-nvidia` exposes, you can ask there https://github.com/huggingface/optimum-nvidia, the only parameter I can see in the readme/doc is `use_fp8=True` which handles the quantization logic, other quantization schemes seem to be in progress https://github.com/huggingface/optimum-nvidia/blob/main/src/optimum/nvidia/quantization/awq.py

Oh I got it. The problem is related to fp8, which A10 arch does not support.
