### ISSUE TITLE
deepspeed  call init_process_group error on qwen/bloom models

### ISSUE THREAD

**Issue by pfk-beta** [huggingface/optimum-benchmark#146]
Hello,
I'm trying to reproduce benchmark inference of qwen or blooms models using deepspeed. But I'm getting following error

stacktrace:
```
[PROC-0][2024-03-05 11:09:09,415][experiment][ERROR] - Error during backend allocation: Default process group has not been initialized, please make sure to call init_process_group.
[2024-03-05 11:09:10,426][experiment][ERROR] - Error during experiment launching: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/workspace/.env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 68, in _wrap
    fn(i, *args)
  File "/workspace/optimum-benchmark/optimum_benchmark/launchers/process/launcher.py", line 58, in entrypoint
    worker_output = worker(*worker_args)
  File "/workspace/optimum-benchmark/optimum_benchmark/experiment.py", line 64, in run
    raise e
  File "/workspace/optimum-benchmark/optimum_benchmark/experiment.py", line 61, in run
    backend: Backend = backend_factory(backend_config)
  File "/workspace/optimum-benchmark/optimum_benchmark/backends/pytorch/backend.py", line 77, in __init__
    self.load_model_with_no_weights()
  File "/workspace/optimum-benchmark/optimum_benchmark/backends/pytorch/backend.py", line 233, in load_model_with_no_weights
    self.load_model_from_pretrained()
  File "/workspace/optimum-benchmark/optimum_benchmark/backends/pytorch/backend.py", line 166, in load_model_from_pretrained
    torch.distributed.barrier()  # better safe than hanging
  File "/workspace/.env/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/workspace/.env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3428, in barrier
    opts.device = _get_pg_default_device(group)
  File "/workspace/.env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 644, in _get_pg_default_device
    group = group or _get_default_group()
  File "/workspace/.env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 977, in _get_default_group
    raise ValueError(
ValueError: Default process group has not been initialized, please make sure to call init_process_group.

Error executing job with overrides: []
Traceback (most recent call last):
  File "/workspace/optimum-benchmark/optimum_benchmark/cli.py", line 63, in benchmark_cli
    benchmark_report: BenchmarkReport = launch(experiment_config=experiment_config)
  File "/workspace/optimum-benchmark/optimum_benchmark/experiment.py", line 141, in launch
    raise e
  File "/workspace/optimum-benchmark/optimum_benchmark/experiment.py", line 136, in launch
    output = launcher.launch(run, benchmark_config, backend_config)
  File "/workspace/optimum-benchmark/optimum_benchmark/launchers/process/launcher.py", line 42, in launch
    while not process_context.join():
  File "/workspace/.env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 158, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/workspace/.env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 68, in _wrap
    fn(i, *args)
  File "/workspace/optimum-benchmark/optimum_benchmark/launchers/process/launcher.py", line 58, in entrypoint
    worker_output = worker(*worker_args)
  File "/workspace/optimum-benchmark/optimum_benchmark/experiment.py", line 64, in run
    raise e
  File "/workspace/optimum-benchmark/optimum_benchmark/experiment.py", line 61, in run
    backend: Backend = backend_factory(backend_config)
  File "/workspace/optimum-benchmark/optimum_benchmark/backends/pytorch/backend.py", line 77, in __init__
    self.load_model_with_no_weights()
  File "/workspace/optimum-benchmark/optimum_benchmark/backends/pytorch/backend.py", line 233, in load_model_with_no_weights
    self.load_model_from_pretrained()
  File "/workspace/optimum-benchmark/optimum_benchmark/backends/pytorch/backend.py", line 166, in load_model_from_pretrained
    torch.distributed.barrier()  # better safe than hanging
  File "/workspace/.env/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/workspace/.env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3428, in barrier
    opts.device = _get_pg_default_device(group)
  File "/workspace/.env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 644, in _get_pg_default_device
    group = group or _get_default_group()
  File "/workspace/.env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 977, in _get_default_group
    raise ValueError(
ValueError: Default process group has not been initialized, please make sure to call init_process_group.


Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

```

Config:
```
defaults:
  - backend: pytorch # default backend
  - launcher: process # default launcher
  - benchmark: inference # default benchmark
  - experiment # inheriting experiment schema
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

experiment_name: test

backend:
  device: cuda
  device_ids: 0
  no_weights: true
  model: Qwen/Qwen1.5-4B-Chat
  deepspeed_inference: true

launcher:
  device_isolation: true

benchmark:
  input_shapes:
    batch_size: 1
    sequence_length: 256
  new_tokens: 1000

# hydra/cli specific settings
hydra:
  run:
    # where to store run results
    dir: runs/${experiment_name}
  sweep:
    # where to store sweep results
    dir: sweeps/${experiment_name}
  job:
    # change working directory to the run directory
    chdir: true
    env_set:
      # set environment variable OVERRIDE_BENCHMARKS to 1
      # to not skip benchmarks that have been run before
      OVERRIDE_BENCHMARKS: 1

```

rtx2080, cuda12

**Comment by IlyasMoutawwakil** [comment]
@pfk-beta `deepspeed-inference` is a distributed inference framework, it should be used with `torchrun` launcher
