### ISSUE TITLE
Moving model to one device

### ISSUE THREAD

**Issue by pfk-beta** [huggingface/optimum-benchmark#148]
Some of the models failed during benchmarking with following error:
```
    File "/workspace/.env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
    File "/workspace/.env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
      return forward_call(*args, **kwargs)
    File "/workspace/.env/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
      return F.embedding(
    File "/workspace/.env/lib/python3.10/site-packages/torch/nn/functional.py", line 2233, in embedding
      return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
  RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)

```

Is this problem of optimum-benchmark, or specific to benchmarked models?

**Comment by IlyasMoutawwakil** [comment]
please provide more details (the used or resulting experiment configuration) for reproduction.
this seems like a `device_map` map error, for example using `device=cpu` (so inputs will be on cpu) and `device_map=auto` will result in device mismatch.

**Comment by IlyasMoutawwakil** [comment]
@pfk-beta does this solve your issue ?

**Comment by pfk-beta** [comment]
There is possibility that my hardware/driver setup was incorrect. I will close issue for now. If I reproduce problem, then I will reopen/recreate issue. Thanks for your effort :)

**Comment by pfk-beta** [comment]
It doesn't look like problem in my hardware/driver setup now. I have used script to run:
```python
import torch

from optimum_benchmark.logging_utils import setup_logging
from optimum_benchmark.experiment import launch, ExperimentConfig

from optimum_benchmark.backends.pytorch.config import PyTorchConfig
from optimum_benchmark.launchers.torchrun.config import TorchrunConfig
from optimum_benchmark.launchers.process.config import ProcessConfig
from optimum_benchmark.benchmarks.inference.config import InferenceConfig


if __name__ == "__main__":
    setup_logging(level="INFO")
    launcher_config = ProcessConfig(device_isolation=True)
    # launcher_config = TorchrunConfig(nproc_per_node=1)
    # launcher_config = TorchrunConfig(device_isolation=True)
    # benchmark_config = InferenceConfig(latency=True, memory=True)
    benchmark_config = InferenceConfig(latency=True, memory=True, input_shapes={'batch_size': 1})
    hub_kwargs = {
        'trust_remote_code': True
    }
    backend_config = PyTorchConfig(
        model="THUDM/chatglm3-6b", device="cuda", device_ids="0", no_weights=True, hub_kwargs=hub_kwargs)

    experiment_config = ExperimentConfig(
        experiment_name="api-launch",
        benchmark=benchmark_config,
        launcher=launcher_config,
        backend=backend_config,
    )
    benchmark_report = launch(experiment_config)

    print(backend_config.model)
    print(torch.cuda.get_device_name(0))

```


Stacktrace:
```python
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/workspace/.env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/home/projects/optimum-benchmark/optimum_benchmark/launchers/process/launcher.py", line 58, in entrypoint
    worker_output = worker(*worker_args)
  File "/home/projects/optimum-benchmark/optimum_benchmark/experiment.py", line 82, in run
    raise e
  File "/home/projects/optimum-benchmark/optimum_benchmark/experiment.py", line 77, in run
    benchmark.run(backend)
  File "/home/projects/optimum-benchmark/optimum_benchmark/benchmarks/inference/benchmark.py", line 128, in run
    _ = backend.forward(self.forward_inputs, self.config.forward_kwargs)
  File "/workspace/.env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/projects/optimum-benchmark/optimum_benchmark/backends/pytorch/backend.py", line 330, in forward
    return self.pretrained_model.forward(**inputs, **kwargs)
  File "/nas/tmp/huggingface_home/modules/transformers_modules/THUDM/chatglm3-6b/
9addbe01105ca1939dd60a0e5866a1812be9daea/modeling_chatglm.py", line 941, in forward
    transformer_outputs = self.transformer(
  File "/workspace/.env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/.env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nas/tmp/huggingface_home/modules/transformers_modules/THUDM/chatglm3-6b/
9addbe01105ca1939dd60a0e5866a1812be9daea/modeling_chatglm.py", line 811, in forward
    inputs_embeds = self.embedding(input_ids)
  File "/workspace/.env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/.env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nas/tmp/huggingface_home/modules/transformers_modules/THUDM/chatglm3-6b/
9addbe01105ca1939dd60a0e5866a1812be9daea/modeling_chatglm.py", line 724, in forward
    words_embeddings = self.word_embeddings(input_ids)
  File "/workspace/.env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/.env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/.env/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/workspace/.env/lib/python3.10/site-packages/torch/nn/functional.py", line 2233, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, 
cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)

```
