### ISSUE TITLE
bnb.4bits error: "ValueError: Blockwise quantization only supports 16/32-bit floats, but got torch.uint8"

### ISSUE THREAD

**Issue by lifelongeeek** [huggingface/optimum-benchmark#175]
I get the following error when I try to use `backend.quantization_scheme=bnb` and `backend.quantization_config.load_in_4bit=true`: ValueError: Blockwise quantization only supports 16/32-bit floats, but got torch.uint8.
I was trying to test with model `NousResearch/Llama-2-7b-chat-hf`.
I am using the recent version (commit hash: [93f5bbc](https://github.com/huggingface/optimum-benchmark/commit/93f5bbc9ff1fc8a4820ee2709c7833f48e8571c1)) of optimum-benchmark.
Here I attach the config and detail log below:

### Config
```
defaults:
  - backend: pytorch # default backend
  - launcher: process # default launcher
  - benchmark: inference # default benchmark
  - experiment # inheriting experiment schema
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

experiment_name: llama-2-7b_bnb4bits

backend:
  quantization_config:
    load_in_4bit: true
  quantization_scheme: bnb
  torch_dtype: bfloat16 #float16
  device: cuda
  device_ids: 0
  no_weights: true
  model: NousResearch/Llama-2-7b-chat-hf #meta-llama/Llama-2-7b-hf

#launcher: # this will make multiprocessing error
#  device_isolation: true

benchmark:
  input_shapes:
    batch_size: 1
    sequence_length: 256
  new_tokens: 256

# hydra/cli specific settings
hydra:
  run:
    # where to store run results
    dir: runs/${experiment_name}
  sweep:
    # where to store sweep results
    dir: sweeps/${experiment_name}
  job:
    # change working directory to the run directory
    chdir: true
    env_set:
      # set environment variable OVERRIDE_BENCHMARKS to 1
      # to not skip benchmarks that have been run before
      OVERRIDE_BENCHMARKS: 1

```
### Detail log
```
ubuntu@gpu-1:$ HYDRA_FULL_ERROR=1 optimum-benchmark --config-dir examples --config-name llama-2-7b_bnb4bits
[2024-04-02 16:44:13,648][inference][WARNING] - `new_tokens` is deprecated. Use `max_new_tokens` and `min_new_tokens` instead. Setting `max_new_tokens` and `min_new_tokens` to `new_tokens`.
[2024-04-02 16:44:13,653][launcher][INFO] - ََAllocating process launcher
[2024-04-02 16:44:13,654][process][INFO] - 	+ Setting multiprocessing start method to spawn.
[2024-04-02 16:44:13,658][process][INFO] - 	+ Launched worker process(es) with PID(s): [4022977]
[PROC-0][2024-04-02 16:44:17,034][backend][INFO] - َAllocating pytorch backend
[PROC-0][2024-04-02 16:44:17,034][backend][INFO] - 	+ Setting random seed to 42
tokenizer_config.json: 100%|█████████████████████████████████████████████████████████████| 746/746 [00:00<00:00, 3.09MB/s]
config.json: 100%|███████████████████████████████████████████████████████████████████████| 583/583 [00:00<00:00, 2.63MB/s]
tokenizer.model: 100%|█████████████████████████████████████████████████████████████████| 500k/500k [00:00<00:00, 20.1MB/s]
tokenizer.json: 100%|████████████████████████████████████████████████████████████████| 1.84M/1.84M [00:00<00:00, 2.08MB/s]
added_tokens.json: 100%|████████████████████████████████████████████████████████████████| 21.0/21.0 [00:00<00:00, 148kB/s]
special_tokens_map.json: 100%|███████████████████████████████████████████████████████████| 435/435 [00:00<00:00, 2.91MB/s]
generation_config.json: 100%|█████████████████████████████████████████████████████████████| 179/179 [00:00<00:00, 997kB/s]
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:492: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:497: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:492: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:497: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
[PROC-0][2024-04-02 16:44:27,158][pytorch][INFO] - 	+ Using AutoModel class AutoModelForCausalLM
[PROC-0][2024-04-02 16:44:27,158][pytorch][INFO] - 	+ Processing quantization config
[PROC-0][2024-04-02 16:44:27,158][pytorch][INFO] - 	+ Processing BitsAndBytes config
[PROC-0][2024-04-02 16:44:27,159][pytorch][INFO] - 	+ Creating backend temporary directory
[PROC-0][2024-04-02 16:44:27,159][pytorch][INFO] - 	+ Loading model with random weights
[PROC-0][2024-04-02 16:44:27,160][pytorch][INFO] - 	+ Creating no weights model
[PROC-0][2024-04-02 16:44:27,160][pytorch][INFO] - 	+ Creating no weights model directory
[PROC-0][2024-04-02 16:44:27,161][pytorch][INFO] - 	+ Creating no weights model state dict
[PROC-0][2024-04-02 16:44:27,163][pytorch][INFO] - 	+ Saving no weights model safetensors
[PROC-0][2024-04-02 16:44:27,164][pytorch][INFO] - 	+ Adding quantization config to no weights model's pretrained config
[PROC-0][2024-04-02 16:44:27,164][pytorch][INFO] - 	+ Saving no weights model pretrained config
[PROC-0][2024-04-02 16:44:27,166][pytorch][INFO] - 	+ Loading no weights AutoModel
[PROC-0][2024-04-02 16:44:27,166][pytorch][INFO] - 	+ Loading Quantized model
/usr/local/lib/python3.10/dist-packages/transformers/quantizers/auto.py:159: UserWarning: You passed `quantization_config` or equivalent parameters to `from_pretrained` but the model you're loading already has a `quantization_config` attribute. The `quantization_config` from the model will be used.
  warnings.warn(warning_msg)
A.dtype = torch.float16
A.dtype = torch.uint8
[PROC-0][2024-04-02 16:44:30,465][experiment][ERROR] - Error during backend allocation: Blockwise quantization only supports 16/32-bit floats, but got torch.uint8
[2024-04-02 16:44:31,473][experiment][ERROR] - Error during experiment launching: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/data/gmkim/optimum-benchmark/optimum_benchmark/launchers/process/launcher.py", line 58, in entrypoint
    worker_output = worker(*worker_args)
  File "/data/gmkim/optimum-benchmark/optimum_benchmark/experiment.py", line 68, in run
    raise e
  File "/data/gmkim/optimum-benchmark/optimum_benchmark/experiment.py", line 65, in run
    backend: Backend = backend_factory(backend_config)
  File "/data/gmkim/optimum-benchmark/optimum_benchmark/backends/pytorch/backend.py", line 81, in __init__
    self.load_model_with_no_weights()
  File "/data/gmkim/optimum-benchmark/optimum_benchmark/backends/pytorch/backend.py", line 243, in load_model_with_no_weights
    self.load_model_from_pretrained()
  File "/data/gmkim/optimum-benchmark/optimum_benchmark/backends/pytorch/backend.py", line 183, in load_model_from_pretrained
    self.pretrained_model = self.automodel_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3589, in from_pretrained
    dispatch_model(model, **device_map_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/accelerate/big_modeling.py", line 396, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 517, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 156, in add_hook_to_module
    module = hook.init_hook(module)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 254, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 339, in set_module_tensor_to_device
    new_value = param_cls(new_value, requires_grad=old_value.requires_grad).to(device)
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/nn/modules.py", line 313, in to
    return self._quantize(device)
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/nn/modules.py", line 280, in _quantize
    w_4bit, quant_state = bnb.functional.quantize_4bit(
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/functional.py", line 1011, in quantize_4bit
    raise ValueError(f"Blockwise quantization only supports 16/32-bit floats, but got {A.dtype}")
ValueError: Blockwise quantization only supports 16/32-bit floats, but got torch.uint8

Error executing job with overrides: []
Traceback (most recent call last):
  File "/usr/local/bin/optimum-benchmark", line 8, in <module>
    sys.exit(benchmark_cli())
  File "/usr/local/lib/python3.10/dist-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/usr/local/lib/python3.10/dist-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/usr/local/lib/python3.10/dist-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/data/gmkim/optimum-benchmark/optimum_benchmark/cli.py", line 63, in benchmark_cli
    benchmark_report: BenchmarkReport = launch(experiment_config=experiment_config)
  File "/data/gmkim/optimum-benchmark/optimum_benchmark/experiment.py", line 153, in launch
    raise e
  File "/data/gmkim/optimum-benchmark/optimum_benchmark/experiment.py", line 148, in launch
    output = launcher.launch(run, benchmark_config, backend_config)
  File "/data/gmkim/optimum-benchmark/optimum_benchmark/launchers/process/launcher.py", line 42, in launch
    while not process_context.join():
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 163, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/data/gmkim/optimum-benchmark/optimum_benchmark/launchers/process/launcher.py", line 58, in entrypoint
    worker_output = worker(*worker_args)
  File "/data/gmkim/optimum-benchmark/optimum_benchmark/experiment.py", line 68, in run
    raise e
  File "/data/gmkim/optimum-benchmark/optimum_benchmark/experiment.py", line 65, in run
    backend: Backend = backend_factory(backend_config)
  File "/data/gmkim/optimum-benchmark/optimum_benchmark/backends/pytorch/backend.py", line 81, in __init__
    self.load_model_with_no_weights()
  File "/data/gmkim/optimum-benchmark/optimum_benchmark/backends/pytorch/backend.py", line 243, in load_model_with_no_weights
    self.load_model_from_pretrained()
  File "/data/gmkim/optimum-benchmark/optimum_benchmark/backends/pytorch/backend.py", line 183, in load_model_from_pretrained
    self.pretrained_model = self.automodel_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3589, in from_pretrained
    dispatch_model(model, **device_map_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/accelerate/big_modeling.py", line 396, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 517, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 156, in add_hook_to_module
    module = hook.init_hook(module)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 254, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 339, in set_module_tensor_to_device
    new_value = param_cls(new_value, requires_grad=old_value.requires_grad).to(device)
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/nn/modules.py", line 313, in to
    return self._quantize(device)
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/nn/modules.py", line 280, in _quantize
    w_4bit, quant_state = bnb.functional.quantize_4bit(
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/functional.py", line 1011, in quantize_4bit
    raise ValueError(f"Blockwise quantization only supports 16/32-bit floats, but got {A.dtype}")
ValueError: Blockwise quantization only supports 16/32-bit floats, but got torch.uint8
```

**Comment by IlyasMoutawwakil** [comment]
Hi, I just ran your configuration and it works fine so the issue might be related to the packages you have installed 
`bnb` has been added lately to the continuously tested configs https://github.com/huggingface/optimum-benchmark/blob/main/tests/configs/_bnb_.yaml.
I would suggest updating your packages or using docker for a clean environment:
```
make build_docker_cuda
make run_docker_cuda
pip install -e .
```

**Comment by lifelongeeek** [comment]
Using docker for a clean environemnt resolve the issue.
Thanks for the solution. Closing the issue.
