### ISSUE TITLE
CUDA_VISIBLE_DEVICES aren't working

### ISSUE THREAD

**Issue by sashavor** [huggingface/optimum-benchmark#176]
When I run the optimum benchmarking code with a `cuda` device in the config, it doesn't see my GPU:
```
optimum-benchmark --config-dir examples/ --config-name energy_star
[2024-04-04 11:35:53,609][launcher][INFO] - ََAllocating process launcher
[2024-04-04 11:35:53,609][process][INFO] - 	+ Setting multiprocessing start method to spawn.
[2024-04-04 11:35:53,620][device-isolation][INFO] - 	+ Launched device(s) isolation process 96990.
[2024-04-04 11:35:53,625][process][INFO] - 	+ Launched benchmark in isolated process 96991.
Process Process-1:
Traceback (most recent call last):
  File "/home/sasha/anaconda3/envs/energystarai/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sasha/anaconda3/envs/energystarai/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sasha/Documents/HuggingFace/optimum-benchmark/optimum_benchmark/launchers/isolation_utils.py", line 113, in assert_system_devices_isolation
    devices_pids = get_pids_running_on_system_devices()
  File "/home/sasha/Documents/HuggingFace/optimum-benchmark/optimum_benchmark/launchers/isolation_utils.py", line 99, in get_pids_running_on_system_devices
    devices_pids = get_nvidia_devices_pids()
  File "/home/sasha/Documents/HuggingFace/optimum-benchmark/optimum_benchmark/launchers/isolation_utils.py", line 44, in get_nvidia_devices_pids
    devices_ids = [int(device_id) for device_id in os.environ["CUDA_VISIBLE_DEVICES"].split(",")]
  File "/home/sasha/anaconda3/envs/energystarai/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'CUDA_VISIBLE_DEVICES'
[PROC-0][2024-04-04 11:35:55,780][datasets][INFO] - PyTorch version 2.2.1 available.
[PROC-0][2024-04-04 11:35:55,938][backend][INFO] - َAllocating pytorch backend
[PROC-0][2024-04-04 11:35:55,938][backend][INFO] - 	+ Setting random seed to 42
[PROC-0][2024-04-04 11:35:56,564][pytorch][INFO] - 	+ Using AutoModel class AutoModel
[PROC-0][2024-04-04 11:35:56,564][pytorch][INFO] - 	+ Creating backend temporary directory
[PROC-0][2024-04-04 11:35:56,565][pytorch][INFO] - 	+ Loading model with random weights
[PROC-0][2024-04-04 11:35:56,565][pytorch][INFO] - 	+ Creating no weights model
[PROC-0][2024-04-04 11:35:56,565][pytorch][INFO] - 	+ Creating no weights model directory
[PROC-0][2024-04-04 11:35:56,565][pytorch][INFO] - 	+ Creating no weights model state dict
[PROC-0][2024-04-04 11:35:56,566][pytorch][INFO] - 	+ Saving no weights model safetensors
[PROC-0][2024-04-04 11:35:56,567][pytorch][INFO] - 	+ Saving no weights model pretrained config
[PROC-0][2024-04-04 11:35:56,568][pytorch][INFO] - 	+ Loading no weights AutoModel
[PROC-0][2024-04-04 11:35:56,568][pytorch][INFO] - 	+ Loading model directly on device: cpu
[PROC-0][2024-04-04 11:35:57,810][pytorch][INFO] - 	+ Turning on model's eval mode
[PROC-0][2024-04-04 11:35:57,814][benchmark][INFO] - Allocating energy_star benchmark
[PROC-0][2024-04-04 11:35:57,814][energy_star][INFO] - 	+ Loading dataset
[PROC-0][2024-04-04 11:36:01,932][energy_star][INFO] - 	+ Preprocessing dataset
[PROC-0][2024-04-04 11:36:06,367][energy_star][INFO] - 	+ Initialising dataloader
[PROC-0][2024-04-04 11:36:06,367][energy_star][INFO] - 	+ Initializing Inference report
[PROC-0][2024-04-04 11:36:06,367][energy_star][INFO] - 	+ Preparing backend for Inference
[PROC-0][2024-04-04 11:36:06,367][energy_star][INFO] - 	+ Warming up backend for Inference
[PROC-0][2024-04-04 11:36:06,598][energy_star][INFO] - 	+ Running energy tracking
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 10.72it/s]
[PROC-0][2024-04-04 11:36:11,932][energy][INFO] - 		+ forward CPU energy: 0.000006 (kWh)
[PROC-0][2024-04-04 11:36:11,932][energy][INFO] - 		+ forward GPU energy: 0.000006 (kWh)
[PROC-0][2024-04-04 11:36:11,932][energy][INFO] - 		+ forward RAM energy: 0.000000 (kWh)
[PROC-0][2024-04-04 11:36:11,932][energy][INFO] - 		+ forward total energy: 0.000012 (kWh)
[PROC-0][2024-04-04 11:36:11,932][energy][INFO] - 		+ preprocess CPU energy: 0.000000 (kWh)
[PROC-0][2024-04-04 11:36:11,932][energy][INFO] - 		+ preprocess GPU energy: 0.000000 (kWh)
[PROC-0][2024-04-04 11:36:11,932][energy][INFO] - 		+ preprocess RAM energy: 0.000000 (kWh)
[PROC-0][2024-04-04 11:36:11,932][energy][INFO] - 		+ preprocess total energy: 0.000000 (kWh)
[PROC-0][2024-04-04 11:36:11,933][energy][INFO] - 		+ forward efficiency: 848920.062342 (samples/kWh)
[PROC-0][2024-04-04 11:36:11,933][energy][INFO] - 		+ preprocess efficiency: 24438423.246041 (samples/kWh)
[2024-04-04 11:36:12,275][device-isolation][INFO] - 	+ Closing device(s) isolation process...
[2024-04-04 11:36:12,297][datasets][INFO] - PyTorch version 2.2.1 available.
```

However, when I do  `CUDA_VISIBLE_DEVICES=0 optimum-benchmark --config-dir examples/ --config-name energy_star` the code runs on GPU (and `echo $CUDA_VISIBLE_DEVICES` and `nvidia-smi` both show available GPUs).

Pytorch also seems to see them (when called from command line python):
```
 import torch
>>> torch.cuda.device_count()
1
```
I'll be explicitly setting  `CUDA_VISIBLE_DEVICES=0` when calling optimum-benchmark, but just wanted to flag the issue :hugs: 

Thank you @regisss for helping me find a fix for now!

**Comment by regisss** [comment]
My understanding is that the code assumes that the env variable `CUDA_VISIBLE_DEVICES` always exists [here](https://github.com/huggingface/optimum-benchmark/blob/1f9d6451269c44786f5e5a7f6f0c611fcb20aeb1/optimum_benchmark/launchers/isolation_utils.py#L44) but it seems that is not necessarily the case: https://stackoverflow.com/questions/67730572/keyerror-cuda-visible-devices#comment119721259_67730572

**Comment by IlyasMoutawwakil** [comment]
that's weird, it's only the device isolation process that doesn't see `CUDA_VISIBLE_DEVICES` in this case (that's why the benchmark still runs successfully), but it works in a clean docker environment (`CUDA_VISIBLE_DEVICES` no set manually), I just added `device_isolation` in all tested configs yesterday https://github.com/huggingface/optimum-benchmark/blob/main/tests/configs/_device_isolation_.yaml and it works in the CI.

@regisss `CUDA_VISIBLE_DEVICES` is set by the backend config when instantiated using `device_ids` here https://github.com/huggingface/optimum-benchmark/blob/1f9d6451269c44786f5e5a7f6f0c611fcb20aeb1/optimum_benchmark/backends/config.py#L68-L76
the `__post_init__` code is triggered very early by the CLI here: https://github.com/huggingface/optimum-benchmark/blob/1f9d6451269c44786f5e5a7f6f0c611fcb20aeb1/optimum_benchmark/cli.py#L61-L63
and then the env var is transferred to the spawned isolation process automatically.

**Comment by sashavor** [comment]
What do you mean by "passing the device ids explicitly between processes"? 

if I just try that branch without specifying the device, it gives the same error:

```
optimum-benchmark --config-dir examples/ --config-name energy_star
[2024-04-05 09:02:42,710][launcher][INFO] - ََAllocating process launcher
[2024-04-05 09:02:42,711][process][INFO] - 	+ Setting multiprocessing start method to spawn.
[2024-04-05 09:02:42,745][device-isolation][INFO] - 	+ Launched device(s) isolation process 124513.
[2024-04-05 09:02:42,751][process][INFO] - 	+ Launched benchmark in isolated process 124514.
Process Process-1:
Traceback (most recent call last):
  File "/home/sasha/anaconda3/envs/energystarai/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sasha/anaconda3/envs/energystarai/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sasha/Documents/HuggingFace/optimum-benchmark/optimum_benchmark/launchers/isolation_utils.py", line 113, in assert_system_devices_isolation
    devices_pids = get_pids_running_on_system_devices()
  File "/home/sasha/Documents/HuggingFace/optimum-benchmark/optimum_benchmark/launchers/isolation_utils.py", line 99, in get_pids_running_on_system_devices
    devices_pids = get_nvidia_devices_pids()
  File "/home/sasha/Documents/HuggingFace/optimum-benchmark/optimum_benchmark/launchers/isolation_utils.py", line 44, in get_nvidia_devices_pids
    devices_ids = [int(device_id) for device_id in os.environ["CUDA_VISIBLE_DEVICES"].split(",")]
  File "/home/sasha/anaconda3/envs/energystarai/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'CUDA_VISIBLE_DEVICES'

```
