### ISSUE TITLE
TypeError: DiffusionPipeline.from_pretrained() got multiple values for argument 'pretrained_model_name_or_path'

### ISSUE THREAD

**Issue by pinjiang** [huggingface/optimum-benchmark#207]
Execute benchmark with Hydra CLI, Get Errors below. The config yaml is attached as .txt
user@06d8461fae8f:/optimum-benchmark$ optimum-benchmark --config-dir ./examples --config-name diffusion_cuda.yaml

[MAIN-PROCESS][2024-05-16 15:20:19,735][backend][WARNING] - `device_ids` was not specified, using all available GPUs.
[MAIN-PROCESS][2024-05-16 15:20:19,735][backend][WARNING] - `device_ids` is now set to `0` based on system configuration.
[MAIN-PROCESS][2024-05-16 15:20:19,738][launcher][INFO] - Allocating process launcher
[MAIN-PROCESS][2024-05-16 15:20:19,738][process][INFO] - 	+ Setting multiprocessing start method to spawn.
[ISOLATED-PROCESS][2024-05-16 15:20:22,982][process][INFO] - Running benchmark in isolated process [1087].
[ISOLATED-PROCESS][2024-05-16 15:20:22,995][backend][INFO] - Allocating pytorch backend
[ISOLATED-PROCESS][2024-05-16 15:20:22,996][backend][INFO] - 	+ Setting random seed to 42
/home/user/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
[ISOLATED-PROCESS][2024-05-16 15:20:26,341][pytorch][INFO] - 	+ Using Diffusers Pipeline AutoPipelineForText2Image
[ISOLATED-PROCESS][2024-05-16 15:20:26,341][pytorch][INFO] - 	+ Creating backend temporary directory
[ISOLATED-PROCESS][2024-05-16 15:20:26,349][pytorch][INFO] - 	+ Loading model with pretrained weights
[ISOLATED-PROCESS][2024-05-16 15:20:26,350][pytorch][INFO] - 	+ Loading Diffusion Pipeline
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/optimum-benchmark/optimum_benchmark/launchers/process/launcher.py", line 64, in target
    report = worker(*worker_args)
  File "/optimum-benchmark/optimum_benchmark/base.py", line 60, in run
    backend: Backend = backend_factory(backend_config)
  File "/optimum-benchmark/optimum_benchmark/backends/pytorch/backend.py", line 88, in __init__
    self.load_model_from_pretrained()
  File "/optimum-benchmark/optimum_benchmark/backends/pytorch/backend.py", line 161, in load_model_from_pretrained
    self.pretrained_model = self.automodel_class.from_pretrained(
  File "/home/user/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/diffusers/pipelines/auto_pipeline.py", line 335, in from_pretrained
    return text_2_image_cls.from_pretrained(pretrained_model_or_path, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
TypeError: DiffusionPipeline.from_pretrained() got multiple values for argument 'pretrained_model_name_or_path'
[diffusion_cuda.txt](https://github.com/huggingface/optimum-benchmark/files/15338057/diffusion_cuda.txt)

**Comment by IlyasMoutawwakil** [comment]
Thanks for spotting this one ! will be fixed in #208
