### ISSUE TITLE
Support for MacOS with M1/M2 silicon and aarch64

### ISSUE THREAD

**Issue by ZexinLi0w0** [huggingface/optimum-benchmark#33]
It seems that MacOS with M1/M2 silicon and aarch64 built (NVIDIA Jetson Toolkits) are not supported right now. I get stuck in stalling GPU benchmarks requirements. The full error log is attached below.

Hardware: Macbook Pro with M2 silicon
Software: macOS Sonoma version 14.0 Beta
Python version: 3.10.8
```
$ pip install -r gpu_requirements.txt
Collecting optimum[onnxruntime-gpu]@ git+https://github.com/huggingface/optimum.git
  Cloning https://github.com/huggingface/optimum.git to /private/var/folders/vn/l1zhdbrs2h39kbdgybz2hds00000gn/T/pip-install-csbfb5uq/optimum_0bccc6844bad4360b8f88a7e8920f7b9
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/optimum.git /private/var/folders/vn/l1zhdbrs2h39kbdgybz2hds00000gn/T/pip-install-csbfb5uq/optimum_0bccc6844bad4360b8f88a7e8920f7b9
  Resolved https://github.com/huggingface/optimum.git to commit 0b08a1fd19005b7334aa923433b3544bd2b11ff2
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting git+https://github.com/huggingface/accelerate.git (from -r gpu_requirements.txt (line 4))
  Cloning https://github.com/huggingface/accelerate.git to /private/var/folders/vn/l1zhdbrs2h39kbdgybz2hds00000gn/T/pip-req-build-16we65zm
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/accelerate.git /private/var/folders/vn/l1zhdbrs2h39kbdgybz2hds00000gn/T/pip-req-build-16we65zm
  Resolved https://github.com/huggingface/accelerate.git to commit d087be01566477d99b660526adb7da4ec31abf1d
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting git+https://github.com/huggingface/transformers.git (from -r gpu_requirements.txt (line 6))
  Cloning https://github.com/huggingface/transformers.git to /private/var/folders/vn/l1zhdbrs2h39kbdgybz2hds00000gn/T/pip-req-build-9q0he8xl
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers.git /private/var/folders/vn/l1zhdbrs2h39kbdgybz2hds00000gn/T/pip-req-build-9q0he8xl
  Resolved https://github.com/huggingface/transformers.git to commit 1982dd3b15867c46e1c20645901b0de469fd935f
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting git+https://github.com/huggingface/diffusers.git (from -r gpu_requirements.txt (line 8))
  Cloning https://github.com/huggingface/diffusers.git to /private/var/folders/vn/l1zhdbrs2h39kbdgybz2hds00000gn/T/pip-req-build-eclppbx1
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/diffusers.git /private/var/folders/vn/l1zhdbrs2h39kbdgybz2hds00000gn/T/pip-req-build-eclppbx1
  Resolved https://github.com/huggingface/diffusers.git to commit 74d902eb59f873b6156621220937f8e2521dfdc0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting omegaconf==2.3.0
  Downloading omegaconf-2.3.0-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 2.1 MB/s eta 0:00:00
Collecting hydra-core==1.3.2
  Downloading hydra_core-1.3.2-py3-none-any.whl (154 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.5/154.5 kB 3.8 MB/s eta 0:00:00
Collecting hydra_colorlog==1.2.0
  Downloading hydra_colorlog-1.2.0-py3-none-any.whl (3.6 kB)
Collecting hydra-joblib-launcher==1.2.0
  Downloading hydra_joblib_launcher-1.2.0-py3-none-any.whl (5.2 kB)
Collecting psutil==5.9.0
  Downloading psutil-5.9.0.tar.gz (478 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 478.3/478.3 kB 7.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting py3nvml==0.2.7
  Downloading py3nvml-0.2.7-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.5/55.5 kB 6.8 MB/s eta 0:00:00
Collecting flatten_dict
  Downloading flatten_dict-0.4.2-py2.py3-none-any.whl (9.7 kB)
Requirement already satisfied: matplotlib in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from -r gpu_requirements.txt (line 22)) (3.7.1)
Requirement already satisfied: seaborn in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from -r gpu_requirements.txt (line 23)) (0.12.2)
Requirement already satisfied: pandas in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from -r gpu_requirements.txt (line 24)) (2.0.0)
Requirement already satisfied: rich in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from -r gpu_requirements.txt (line 25)) (13.5.2)
Requirement already satisfied: PyYAML>=5.1.0 in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from omegaconf==2.3.0->-r gpu_requirements.txt (line 11)) (6.0)
Collecting antlr4-python3-runtime==4.9.*
  Using cached antlr4-python3-runtime-4.9.3.tar.gz (117 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: packaging in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from hydra-core==1.3.2->-r gpu_requirements.txt (line 12)) (22.0)
Collecting colorlog
  Using cached colorlog-6.7.0-py2.py3-none-any.whl (11 kB)
Collecting joblib>=0.14.0
  Downloading joblib-1.3.2-py3-none-any.whl (302 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.2/302.2 kB 8.7 MB/s eta 0:00:00
Collecting xmltodict
  Downloading xmltodict-0.13.0-py2.py3-none-any.whl (10.0 kB)
Requirement already satisfied: torch>=1.9 in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from optimum[onnxruntime-gpu]@ git+https://github.com/huggingface/optimum.git->-r gpu_requirements.txt (line 2)) (1.14.0.dev20221130)
Requirement already satisfied: numpy in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from optimum[onnxruntime-gpu]@ git+https://github.com/huggingface/optimum.git->-r gpu_requirements.txt (line 2)) (1.24.2)
Requirement already satisfied: sympy in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from optimum[onnxruntime-gpu]@ git+https://github.com/huggingface/optimum.git->-r gpu_requirements.txt (line 2)) (1.11.1)
Requirement already satisfied: huggingface-hub>=0.8.0 in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from optimum[onnxruntime-gpu]@ git+https://github.com/huggingface/optimum.git->-r gpu_requirements.txt (line 2)) (0.11.1)
Collecting datasets
  Downloading datasets-2.14.4-py3-none-any.whl (519 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 519.3/519.3 kB 8.1 MB/s eta 0:00:00
Collecting coloredlogs
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 6.5 MB/s eta 0:00:00
Requirement already satisfied: protobuf>=3.20.1 in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from optimum[onnxruntime-gpu]@ git+https://github.com/huggingface/optimum.git->-r gpu_requirements.txt (line 2)) (4.21.12)
Collecting onnx
  Downloading onnx-1.14.0-cp310-cp310-macosx_10_12_universal2.whl (15.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.2/15.2 MB 9.9 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of antlr4-python3-runtime to determine which version is compatible with other requirements. This could take a while.
Collecting antlr4-python3-runtime==4.9.*
  Downloading antlr4-python3-runtime-4.9.2.tar.gz (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.2/117.2 kB 8.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading antlr4-python3-runtime-4.9.1.tar.gz (173 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 173.3/173.3 kB 6.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading antlr4-python3-runtime-4.9.tar.gz (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 kB 2.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of py3nvml to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of psutil to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of hydra-joblib-launcher to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of hydra-colorlog to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of hydra-core to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of omegaconf to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu>=1.11.0; extra == "onnxruntime-gpu" (from optimum[onnxruntime-gpu]) (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu>=1.11.0; extra == "onnxruntime-gpu"
(torch-gpu)
# zexinli @ Zexins-MacBook-Pro-314 in ~/Downloads/optimum-benchmark on git:main o [16:32:43] C:1
$ pip install -r gpu_requirements.txt
Collecting optimum[onnxruntime-gpu]@ git+https://github.com/huggingface/optimum.git
  Cloning https://github.com/huggingface/optimum.git to /private/var/folders/vn/l1zhdbrs2h39kbdgybz2hds00000gn/T/pip-install-81jr16tx/optimum_1dce106715f042c2948ecf67f789f276
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/optimum.git /private/var/folders/vn/l1zhdbrs2h39kbdgybz2hds00000gn/T/pip-install-81jr16tx/optimum_1dce106715f042c2948ecf67f789f276
  Resolved https://github.com/huggingface/optimum.git to commit 0b08a1fd19005b7334aa923433b3544bd2b11ff2
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting git+https://github.com/huggingface/accelerate.git (from -r gpu_requirements.txt (line 4))
  Cloning https://github.com/huggingface/accelerate.git to /private/var/folders/vn/l1zhdbrs2h39kbdgybz2hds00000gn/T/pip-req-build-k59j88zd
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/accelerate.git /private/var/folders/vn/l1zhdbrs2h39kbdgybz2hds00000gn/T/pip-req-build-k59j88zd
  Resolved https://github.com/huggingface/accelerate.git to commit d087be01566477d99b660526adb7da4ec31abf1d
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting git+https://github.com/huggingface/transformers.git (from -r gpu_requirements.txt (line 6))
  Cloning https://github.com/huggingface/transformers.git to /private/var/folders/vn/l1zhdbrs2h39kbdgybz2hds00000gn/T/pip-req-build-zs4p5wpm
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers.git /private/var/folders/vn/l1zhdbrs2h39kbdgybz2hds00000gn/T/pip-req-build-zs4p5wpm
  Resolved https://github.com/huggingface/transformers.git to commit 1982dd3b15867c46e1c20645901b0de469fd935f
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting git+https://github.com/huggingface/diffusers.git (from -r gpu_requirements.txt (line 8))
  Cloning https://github.com/huggingface/diffusers.git to /private/var/folders/vn/l1zhdbrs2h39kbdgybz2hds00000gn/T/pip-req-build-t4fkfavm
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/diffusers.git /private/var/folders/vn/l1zhdbrs2h39kbdgybz2hds00000gn/T/pip-req-build-t4fkfavm
  Resolved https://github.com/huggingface/diffusers.git to commit 74d902eb59f873b6156621220937f8e2521dfdc0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting omegaconf==2.3.0
  Using cached omegaconf-2.3.0-py3-none-any.whl (79 kB)
Collecting hydra-core==1.3.2
  Using cached hydra_core-1.3.2-py3-none-any.whl (154 kB)
Collecting hydra_colorlog==1.2.0
  Using cached hydra_colorlog-1.2.0-py3-none-any.whl (3.6 kB)
Collecting hydra-joblib-launcher==1.2.0
  Using cached hydra_joblib_launcher-1.2.0-py3-none-any.whl (5.2 kB)
Collecting psutil==5.9.0
  Using cached psutil-5.9.0.tar.gz (478 kB)
  Preparing metadata (setup.py) ... done
Collecting py3nvml==0.2.7
  Using cached py3nvml-0.2.7-py3-none-any.whl (55 kB)
Collecting flatten_dict
  Using cached flatten_dict-0.4.2-py2.py3-none-any.whl (9.7 kB)
Requirement already satisfied: matplotlib in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from -r gpu_requirements.txt (line 22)) (3.7.1)
Requirement already satisfied: seaborn in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from -r gpu_requirements.txt (line 23)) (0.12.2)
Requirement already satisfied: pandas in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from -r gpu_requirements.txt (line 24)) (2.0.0)
Requirement already satisfied: rich in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from -r gpu_requirements.txt (line 25)) (13.5.2)
Collecting antlr4-python3-runtime==4.9.*
  Using cached antlr4-python3-runtime-4.9.3.tar.gz (117 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: PyYAML>=5.1.0 in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from omegaconf==2.3.0->-r gpu_requirements.txt (line 11)) (6.0)
Requirement already satisfied: packaging in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from hydra-core==1.3.2->-r gpu_requirements.txt (line 12)) (22.0)
Collecting colorlog
  Using cached colorlog-6.7.0-py2.py3-none-any.whl (11 kB)
Collecting joblib>=0.14.0
  Using cached joblib-1.3.2-py3-none-any.whl (302 kB)
Collecting xmltodict
  Using cached xmltodict-0.13.0-py2.py3-none-any.whl (10.0 kB)
Collecting datasets
  Using cached datasets-2.14.4-py3-none-any.whl (519 kB)
Requirement already satisfied: huggingface-hub>=0.8.0 in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from optimum[onnxruntime-gpu]@ git+https://github.com/huggingface/optimum.git->-r gpu_requirements.txt (line 2)) (0.11.1)
Requirement already satisfied: sympy in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from optimum[onnxruntime-gpu]@ git+https://github.com/huggingface/optimum.git->-r gpu_requirements.txt (line 2)) (1.11.1)
Requirement already satisfied: numpy in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from optimum[onnxruntime-gpu]@ git+https://github.com/huggingface/optimum.git->-r gpu_requirements.txt (line 2)) (1.24.2)
Collecting coloredlogs
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Requirement already satisfied: torch>=1.9 in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from optimum[onnxruntime-gpu]@ git+https://github.com/huggingface/optimum.git->-r gpu_requirements.txt (line 2)) (1.14.0.dev20221130)
Requirement already satisfied: protobuf>=3.20.1 in /Users/zexinli/miniforge3/envs/torch-gpu/lib/python3.10/site-packages (from optimum[onnxruntime-gpu]@ git+https://github.com/huggingface/optimum.git->-r gpu_requirements.txt (line 2)) (4.21.12)
Collecting onnx
  Using cached onnx-1.14.0-cp310-cp310-macosx_10_12_universal2.whl (15.2 MB)
Collecting evaluate
  Downloading evaluate-0.4.0-py3-none-any.whl (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.4/81.4 kB 2.2 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of antlr4-python3-runtime to determine which version is compatible with other requirements. This could take a while.
Collecting antlr4-python3-runtime==4.9.*
  Using cached antlr4-python3-runtime-4.9.2.tar.gz (117 kB)
  Preparing metadata (setup.py) ... done
  Using cached antlr4-python3-runtime-4.9.1.tar.gz (173 kB)
  Preparing metadata (setup.py) ... done
  Using cached antlr4-python3-runtime-4.9.tar.gz (114 kB)
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of py3nvml to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of psutil to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of hydra-joblib-launcher to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of hydra-colorlog to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of hydra-core to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of omegaconf to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu>=1.11.0; extra == "onnxruntime-gpu" (from optimum[onnxruntime-gpu]) (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu>=1.11.0; extra == "onnxruntime-gpu"
```

Hardware: NVIDIA Jetson AGX Orin
Software: Ubuntu 20.04.6 LTS + Jetpack 5.1.2
Python version: 3.10.0
```
$ pip install -r gpu_requirements.txt
Collecting optimum[onnxruntime-gpu]@ git+https://github.com/huggingface/optimum.git (from -r gpu_requirements.txt (line 2))
  Cloning https://github.com/huggingface/optimum.git to /tmp/pip-install-8nj2u072/optimum_c9c70138577d48cdb2aae7deba08513b
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/optimum.git /tmp/pip-install-8nj2u072/optimum_c9c70138577d48cdb2aae7deba08513b
  Resolved https://github.com/huggingface/optimum.git to commit 0b08a1fd19005b7334aa923433b3544bd2b11ff2
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting git+https://github.com/huggingface/accelerate.git (from -r gpu_requirements.txt (line 4))
  Cloning https://github.com/huggingface/accelerate.git to /tmp/pip-req-build-h2p4r7xx
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/accelerate.git /tmp/pip-req-build-h2p4r7xx
  Resolved https://github.com/huggingface/accelerate.git to commit d087be01566477d99b660526adb7da4ec31abf1d
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting git+https://github.com/huggingface/transformers.git (from -r gpu_requirements.txt (line 6))
  Cloning https://github.com/huggingface/transformers.git to /tmp/pip-req-build-tf3ypbnj
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers.git /tmp/pip-req-build-tf3ypbnj
  Resolved https://github.com/huggingface/transformers.git to commit 1982dd3b15867c46e1c20645901b0de469fd935f
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting git+https://github.com/huggingface/diffusers.git (from -r gpu_requirements.txt (line 8))
  Cloning https://github.com/huggingface/diffusers.git to /tmp/pip-req-build-90vy0vxn
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/diffusers.git /tmp/pip-req-build-90vy0vxn
  Resolved https://github.com/huggingface/diffusers.git to commit 74d902eb59f873b6156621220937f8e2521dfdc0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting omegaconf==2.3.0 (from -r gpu_requirements.txt (line 11))
  Using cached omegaconf-2.3.0-py3-none-any.whl (79 kB)
Collecting hydra-core==1.3.2 (from -r gpu_requirements.txt (line 12))
  Using cached hydra_core-1.3.2-py3-none-any.whl (154 kB)
Collecting hydra_colorlog==1.2.0 (from -r gpu_requirements.txt (line 13))
  Using cached hydra_colorlog-1.2.0-py3-none-any.whl (3.6 kB)
Collecting hydra-joblib-launcher==1.2.0 (from -r gpu_requirements.txt (line 14))
  Using cached hydra_joblib_launcher-1.2.0-py3-none-any.whl (5.2 kB)
Collecting psutil==5.9.0 (from -r gpu_requirements.txt (line 17))
  Using cached psutil-5.9.0.tar.gz (478 kB)
  Preparing metadata (setup.py) ... done
Collecting py3nvml==0.2.7 (from -r gpu_requirements.txt (line 18))
  Using cached py3nvml-0.2.7-py3-none-any.whl (55 kB)
Collecting flatten_dict (from -r gpu_requirements.txt (line 21))
  Using cached flatten_dict-0.4.2-py2.py3-none-any.whl (9.7 kB)
Collecting matplotlib (from -r gpu_requirements.txt (line 22))
  Obtaining dependency information for matplotlib from https://files.pythonhosted.org/packages/64/e1/e7ee2ac522b66aed3022da0ab33b90e7d7f58aa17adbfaf123247598a0af/matplotlib-3.7.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata
  Downloading matplotlib-3.7.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (5.6 kB)
Collecting seaborn (from -r gpu_requirements.txt (line 23))
  Using cached seaborn-0.12.2-py3-none-any.whl (293 kB)
Collecting pandas (from -r gpu_requirements.txt (line 24))
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/c2/59/cb4234bc9b968c57e81861b306b10cd8170272c57b098b724d3de5eda124/pandas-2.0.3-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata
  Downloading pandas-2.0.3-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (18 kB)
Collecting rich (from -r gpu_requirements.txt (line 25))
  Obtaining dependency information for rich from https://files.pythonhosted.org/packages/8d/5f/21a93b2ec205f4b79853ff6e838e3c99064d5dbe85ec6b05967506f14af0/rich-13.5.2-py3-none-any.whl.metadata
  Using cached rich-13.5.2-py3-none-any.whl.metadata (18 kB)
Collecting antlr4-python3-runtime==4.9.* (from omegaconf==2.3.0->-r gpu_requirements.txt (line 11))
  Using cached antlr4-python3-runtime-4.9.3.tar.gz (117 kB)
  Preparing metadata (setup.py) ... done
Collecting PyYAML>=5.1.0 (from omegaconf==2.3.0->-r gpu_requirements.txt (line 11))
  Obtaining dependency information for PyYAML>=5.1.0 from https://files.pythonhosted.org/packages/f1/26/55e4f21db1f72eaef092015d9017c11510e7e6301c62a6cfee91295d13c6/PyYAML-6.0.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata
  Downloading PyYAML-6.0.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (2.1 kB)
Collecting packaging (from hydra-core==1.3.2->-r gpu_requirements.txt (line 12))
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting colorlog (from hydra_colorlog==1.2.0->-r gpu_requirements.txt (line 13))
  Using cached colorlog-6.7.0-py2.py3-none-any.whl (11 kB)
Collecting joblib>=0.14.0 (from hydra-joblib-launcher==1.2.0->-r gpu_requirements.txt (line 14))
  Obtaining dependency information for joblib>=0.14.0 from https://files.pythonhosted.org/packages/10/40/d551139c85db202f1f384ba8bcf96aca2f329440a844f924c8a0040b6d02/joblib-1.3.2-py3-none-any.whl.metadata
  Using cached joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting xmltodict (from py3nvml==0.2.7->-r gpu_requirements.txt (line 18))
  Using cached xmltodict-0.13.0-py2.py3-none-any.whl (10.0 kB)
Collecting coloredlogs (from optimum[onnxruntime-gpu]@ git+https://github.com/huggingface/optimum.git->-r gpu_requirements.txt (line 2))
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Collecting sympy (from optimum[onnxruntime-gpu]@ git+https://github.com/huggingface/optimum.git->-r gpu_requirements.txt (line 2))
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting torch>=1.9 (from optimum[onnxruntime-gpu]@ git+https://github.com/huggingface/optimum.git->-r gpu_requirements.txt (line 2))
  Downloading torch-2.0.1-cp310-cp310-manylinux2014_aarch64.whl (74.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.0/74.0 MB 6.4 MB/s eta 0:00:00
Collecting numpy (from optimum[onnxruntime-gpu]@ git+https://github.com/huggingface/optimum.git->-r gpu_requirements.txt (line 2))
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/b1/39/3f88e2bfac1fb510c112dc0c78a1e7cad8f3a2d75e714d1484a044c56682/numpy-1.25.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata
  Downloading numpy-1.25.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (5.6 kB)
Collecting huggingface-hub>=0.8.0 (from optimum[onnxruntime-gpu]@ git+https://github.com/huggingface/optimum.git->-r gpu_requirements.txt (line 2))
  Obtaining dependency information for huggingface-hub>=0.8.0 from https://files.pythonhosted.org/packages/7f/c4/adcbe9a696c135578cabcbdd7331332daad4d49b7c43688bc2d36b3a47d2/huggingface_hub-0.16.4-py3-none-any.whl.metadata
  Using cached huggingface_hub-0.16.4-py3-none-any.whl.metadata (12 kB)
Collecting datasets (from optimum[onnxruntime-gpu]@ git+https://github.com/huggingface/optimum.git->-r gpu_requirements.txt (line 2))
  Obtaining dependency information for datasets from https://files.pythonhosted.org/packages/66/f8/38298237d18d4b6a8ee5dfe390e97bed5adb8e01ec6f9680c0ddf3066728/datasets-2.14.4-py3-none-any.whl.metadata
  Using cached datasets-2.14.4-py3-none-any.whl.metadata (19 kB)
Collecting onnx (from optimum[onnxruntime-gpu]@ git+https://github.com/huggingface/optimum.git->-r gpu_requirements.txt (line 2))
  Downloading onnx-1.14.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (15.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.0/15.0 MB 8.6 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of optimum[onnxruntime-gpu] to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu>=1.11.0; extra == "onnxruntime-gpu" (from optimum[onnxruntime-gpu]) (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu>=1.11.0; extra == "onnxruntime-gpu"
```

**Comment by IlyasMoutawwakil** [comment]
I don't think either one of those is supported in `onnxruntime-gpu`.
You can `pip install requirements` to get third-party libraries without the backends.
For Jetson, https://elinux.org/Jetson_Zoo#ONNX_Runtime
For M1/M2, https://onnxruntime.ai/docs/execution-providers/CoreML-ExecutionProvider.html#install 
And report any problem you find in the OnnxRuntime repo.

**Comment by IlyasMoutawwakil** [comment]
@regisss do we support these hardware in optimum ?

**Comment by regisss** [comment]
> @regisss do we support these hardware in optimum ?

For M1/M2, it's supported in Transformers: https://huggingface.co/docs/transformers/v4.32.1/en/main_classes/trainer#using-trainer-for-accelerated-pytorch-training-on-mac
So it should be feasible to benchmark with the PyTorch backend.
However, Optimum doesn't support the [ORT's CoreML execution provider](https://onnxruntime.ai/docs/execution-providers/CoreML-ExecutionProvider.html) at the moment.

For Nvidia Jetson, I think it works with: https://elinux.org/Jetson_Zoo#ONNX_Runtime

**Comment by ZexinLi0w0** [comment]
@regisss Thanks for the explanation. For this guidance https://elinux.org/Jetson_Zoo#ONNX_Runtime, optimum is successful to install on Jetson. However, I still encounter some errors when running this smoke test command. 
```
optimum-benchmark --config-dir examples/ --config-name pytorch
```

The error log is 
```
Traceback (most recent call last):
  File "/home/zexin/.conda/envs/profiler/bin/optimum-benchmark", line 5, in <module>
    from optimum_benchmark.main import run_experiment
  File "/home/zexin/.conda/envs/profiler/lib/python3.8/site-packages/optimum_benchmark/main.py", line 95, in <module>
    from optimum_benchmark.backends.pytorch import PyTorchConfig
  File "/home/zexin/.conda/envs/profiler/lib/python3.8/site-packages/optimum_benchmark/backends/pytorch.py", line 11, in <module>
    from torch.distributed.launcher.api import elastic_launch, LaunchConfig
  File "/home/zexin/.conda/envs/profiler/lib/python3.8/site-packages/torch/distributed/launcher/__init__.py", line 10, in <module>
    from torch.distributed.launcher.api import (  # noqa: F401
  File "/home/zexin/.conda/envs/profiler/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 13, in <module>
    import torch.distributed.elastic.rendezvous.registry as rdzv_registry
  File "/home/zexin/.conda/envs/profiler/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/__init__.py", line 131, in <module>
    from .api import *  # noqa: F403
  File "/home/zexin/.conda/envs/profiler/lib/python3.8/site-packages/torch/distributed/elastic/rendezvous/api.py", line 10, in <module>
    from torch.distributed import Store
ImportError: cannot import name 'Store' from 'torch.distributed' (/home/zexin/.conda/envs/profiler/lib/python3.8/site-packages/torch/distributed/__init__.py)
```

It seems that the torch wheels from Jetson has no "distributed" support by default referring to 
https://forums.developer.nvidia.com/t/importerror-cannot-import-name-store-from-torch-distributed/262235.

Does the optimum require torch.distribute to run?

**Comment by regisss** [comment]
@IlyasMoutawwakil I think we should import from `torch.distributed` only if the world size is larger than 1. If I remember well, `torchrun` will store the world size in the `WORLD_SIZE` env variable.

**Comment by IlyasMoutawwakil** [comment]
yes, I will fix it
