### ISSUE TITLE
Issue when running config bert on NVIDIA H100 GPU with latest PyTorch / transformers installed

### ISSUE THREAD

**Issue by x11kjm** [huggingface/optimum-benchmark#8]
Hello, if there are any contribution guildelines for me to modify this issue please let me know! Happy to modify my request.

I attempted to run the bert.yaml configuration with default device=cuda, and was met with the following error. I have the latest transformers installed at 4.31.0. Is there something on my end that needs modification? I was able to run gpt2.yaml!
```
user@ef0083661451:/scratch/projects/optimum_benchmark/optimum-benchmark$ python3 main.py --config-name bert
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
[2023-07-24 22:19:29,535][benchmark][INFO] - Configuring inference benchmark
[2023-07-24 22:19:29,535][benchmark][INFO] -    + Setting seed(42)
[2023-07-24 22:19:31,019][backend][INFO] - Checking initial device isolation
[2023-07-24 22:19:31,078][backend][INFO] - Initial device isolation check passed: no process is running on device cuda
[2023-07-24 22:19:31,078][backend][INFO] - Checking contineous device isolation
[2023-07-24 22:19:31,101][pytorch][INFO] -      + Infered AutoModel class AutoModelForMaskedLM for task fill-mask and model_type bert
[2023-07-24 22:19:31,102][backend][INFO] - Configuring pytorch backend
[2023-07-24 22:19:31,105][pytorch][INFO] -      + Disabling gradients
[2023-07-24 22:19:31,106][pytorch][INFO] -      + Loading pretrained model weights in None on cuda with no quantization
/home/user/.local/lib/python3.8/site-packages/transformers/modeling_utils.py:2193: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.weight', 'cls.seq_relationship.weight', 'bert.pooler.dense.bias', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForMaskedLM were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['cls.predictions.decoder.bias', 'cls.predictions.decoder.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[2023-07-24 22:19:31,870][pytorch][INFO] -      + Turning on eval mode
[2023-07-24 22:19:31,871][inference][INFO] - Running inference benchmark
[2023-07-24 22:19:31,871][backend][INFO] - Generating dummy inputs for ['input_ids', 'attention_mask', 'token_type_ids']
'BertConfig' object has no attribute 'encoder'
'BertConfig' object has no attribute 'decoder'
'BertConfig' object has no attribute 'encoder'
'BertConfig' object has no attribute 'decoder'
'BertConfig' object has no attribute 'encoder'
'BertConfig' object has no attribute 'decoder'
[2023-07-24 22:19:31,875][backend][INFO] - Generating dummy inputs with shapes {'batch_size': 1, 'sequence_length': 16, 'num_choices': 4}
[2023-07-24 22:19:31,875][inference][INFO] -    + Warming up the forward pass
[2023-07-24 22:19:32,015][inference][INFO] -    + Tracking forward pass latency and throughput
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
Otherprocess
Otherprocess
Otherprocess
Otherprocess
Otherprocess
Otherprocess
[2023-07-24 22:19:42,123][inference][INFO] -    + Forward pass latency: 6.42e-03 (s)
[2023-07-24 22:19:42,124][inference][INFO] -    + Forward pass throughput: 156.00 (samples/s)
[2023-07-24 22:19:42,442][backend][INFO] - Generating dummy inputs for ['input_ids', 'token_type_ids', 'attention_mask']
'BertConfig' object has no attribute 'encoder'
'BertConfig' object has no attribute 'decoder'
'BertConfig' object has no attribute 'encoder'
'BertConfig' object has no attribute 'decoder'
'BertConfig' object has no attribute 'encoder'
'BertConfig' object has no attribute 'decoder'
[2023-07-24 22:19:42,443][backend][INFO] - Generating dummy inputs with shapes {'batch_size': 1, 'sequence_length': 16, 'num_choices': 4}
[2023-07-24 22:19:42,443][inference][INFO] -    + Warming up the generation pass
[2023-07-24 22:19:42,443][main][ERROR] - 'BertConfig' object has no attribute 'decoder'
Traceback (most recent call last):
  File "main.py", line 51, in run_experiment
    benchmark.run(backend)
  File "/scratch/projects/optimum_benchmark/optimum-benchmark/src/benchmark/inference.py", line 87, in run
    self.run_generate_tracking(backend)
  File "/scratch/projects/optimum_benchmark/optimum-benchmark/src/benchmark/inference.py", line 123, in run_generate_tracking
    _ = backend.generate(generate_input, new_tokens=self.new_tokens // 10)
  File "/scratch/projects/optimum_benchmark/optimum-benchmark/src/backend/pytorch.py", line 226, in generate
    else self.pretrained_model.config.decoder.eos_token_id,
  File "/home/user/.local/lib/python3.8/site-packages/transformers/configuration_utils.py", line 261, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'BertConfig' object has no attribute 'decoder'
```

Here are a couple of my package versions:
```
user@ef0083661451:/scratch/projects/optimum_benchmark/optimum-benchmark$ python3 -m pip list | grep -E 'transformers|torch|triton'
torch                         2.0.1+cu118
torchaudio                    2.0.2+cu118
torchvision                   0.15.2+cu118
transformers                  4.31.0
triton                        2.0.0
```

**Comment by IlyasMoutawwakil** [comment]
hi @x11kjm thank you for your interest in the repo and for pointing that bug. I fixed it.

**Comment by IlyasMoutawwakil** [comment]
I also merged some big changes to the repo with packaging, tests and workflows. so hopefully it's gonna be more stable starting from now 😊. Don't hesitate to contribute to it!
