### ISSUE TITLE
Issue when checking for other CUDA processes

### ISSUE THREAD

**Issue by x11kjm** [huggingface/optimum-benchmark#9]
Hello, please let me know if you would like any modifications to this ticket if I am missing anything!

I attempted running:
```
python main.py --config-name bert
```
On an NVIDIA H100 GPU with no other processes running, although I was running in a docker container. I was met with the following error:
```
user@5c9009e24c71:/scratch/projects/optimum_benchmark/optimum-benchmark$ python main.py --config-name bert
[2023-07-24 21:51:07,371] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
[2023-07-24 21:51:11,977][benchmark][INFO] - Configuring inference benchmark
[2023-07-24 21:51:11,977][benchmark][INFO] -    + Setting seed(42)
Downloading (…)lve/main/config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 570/570 [00:00<00:00, 183kB/s]
[2023-07-24 21:51:12,678][backend][INFO] - Checking initial device isolation
[2023-07-24 21:51:13,603][backend][INFO] - Initial device isolation check passed: no process is running on device cuda
[2023-07-24 21:51:13,603][backend][INFO] - Checking contineous device isolation
[2023-07-24 21:51:13,614][pytorch][INFO] -      + Infered AutoModel class AutoModelForMaskedLM for task fill-mask and model_type bert
[2023-07-24 21:51:13,615][backend][INFO] - Configuring pytorch backend
[2023-07-24 21:51:13,617][pytorch][INFO] -      + Disabling gradients
[2023-07-24 21:51:13,617][pytorch][INFO] -      + Loading pretrained model weights in None on cuda with no quantization
/home/user/.local/lib/python3.8/site-packages/transformers/modeling_utils.py:2197: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Downloading model.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 440M/440M [00:01<00:00, 306MB/s]
[2023-07-24 21:51:15,339] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForMaskedLM were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['cls.predictions.decoder.bias', 'cls.predictions.decoder.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[2023-07-24 21:51:18,718][pytorch][INFO] -      + Turning on eval mode
[2023-07-24 21:51:18,719][inference][INFO] - Running inference benchmark
[2023-07-24 21:51:18,719][backend][INFO] - Generating dummy inputs for ['input_ids', 'attention_mask', 'token_type_ids']
'BertConfig' object has no attribute 'encoder'
'BertConfig' object has no attribute 'decoder'
'BertConfig' object has no attribute 'encoder'
'BertConfig' object has no attribute 'decoder'
'BertConfig' object has no attribute 'encoder'
'BertConfig' object has no attribute 'decoder'
[2023-07-24 21:51:18,720][backend][INFO] - Generating dummy inputs with shapes {'batch_size': 1, 'sequence_length': 16, 'num_choices': 4}
[2023-07-24 21:51:18,720][inference][INFO] -    + Warming up the forward pass
Process Process-1:
Traceback (most recent call last):
  File "/opt/conda/envs/inference/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/inference/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/projects/optimum_benchmark/optimum-benchmark/src/utils.py", line 171, in check_only_this_process_is_running_on_cuda_device
    raise RuntimeError(
RuntimeError: Expected only process 3178 on device 0, found 1 processes with PIDs {8417}.
Terminated
```

Running `nvidia-smi` did not show any other processes, and I could not find this extra process anywhere, through `nvidia-smi` or `ps aux`. Are there any recommendations on how to run this configuration with `device=cuda`? Thank you so much.

**Comment by IlyasMoutawwakil** [comment]
hmm that's weird I never had this issue with A100. I'm not sure why there's a process other than the main one on your device. If you're sure your environment is isolated and resources are only allocated to your process, you can comment this [line](https://github.com/huggingface/optimum-benchmark/blob/189c983e0e6d19c05c00d7f1e17512b1a48a48d5/src/backend/base.py#L59). I only added it because I usually work in an env with shared resources.

**Comment by IlyasMoutawwakil** [comment]
I will add some control over the isolation checks soon.

**Comment by IlyasMoutawwakil** [comment]
Hi! You can now disable isolation checks with `backend.contineous_isolation_check=false`
https://github.com/huggingface/optimum-benchmark/blob/d336d2170562d26004376acdf6790ac138dabdb4/optimum_benchmark/backends/base.py#L41-L43
